### ISSUE TITLE
[IOS ]Missing Compliance after upload build to testflight

### ISSUE THREAD

**Issue by dungkv-1044** [framgia/div-high-dev-guidelines#5]
Các  anh xem giúp  em với, e upload ipa lên testflight nhưng nó bị lỗi vàng ở bản build đó :Missing Compliance
https://gyazo.com/ce228adbba3886c16e42075069952b93
em xem mấy cái sửa trên stackoverflow thì chúng nó bảo thêm cái 
<key>ITSAppUsesNonExemptEncryption</key><false/>
vào file plist thì k bị nữa mà em thêm ko đc (bow) @ #

**Comment by cong91** [comment]
done
